### ISSUE TITLE
[Qute] empty template throws an error

### ISSUE THREAD

**Issue by angelozerr** [javacc21/blue-sky#2]
When Qute template is empty:

```java
QUTEParser parser = new QUTEParser(new StringReader("") );
parser.Root();

```
it throws the error:

```
Exception in thread "main" qute.ParseException: Encountered "<EOF>" at line 0, column 0 in .
Was expecting one of:
    <TEXT> ...
    "{" ...
    <IF> ...
    <START_SECTION> ...
    
	at qute.QUTEParser.generateParseException(QUTEParser.java:321)
	at qute.QUTEParser.jj_consume_token(QUTEParser.java:251)
	at qute.QUTEParser.Block(QUTEParser.java:786)
	at qute.QUTEParser.Root(QUTEParser.java:834)
	at Test.main(Test.java:15)

```

**Comment by revusky** [comment]
Oh, well, that's easy to fix. Just where you have at the end of QUTE.javacc
void Root() :{}
{
   Block()
   <EOF>
}

Just put square brackets around Block(). 
[Block()]
or: (Block())? is the same thing.

That makes the Block() production optional and it will then successfully parse an empty file. Of course, you have to regenerate everything after that obviously...

**Comment by angelozerr** [comment]
Thanks for your explanation.

is it possible for you to fix it please. For the moment I would like to have the Qute grammar in your repository by waiting for tolerance support from your side.

Thanks!

**Comment by revusky** [comment]
Okay, it's fixed. Again, whenever you want, I'll give you commit rights to this repository. This is just a sandbox anyway.

**Comment by angelozerr** [comment]
Fixed with https://github.com/javacc21/blue-sky/commit/bc2b7eb578d6b57642c32fec2bf358e4f2a8ada2

Thanks @revusky !

**Comment by angelozerr** [comment]
> Again, whenever you want, I'll give you commit rights to this repository. 

As I said you, I would like at first validate if JavaCC21 is a good canditate for Qute and my goal is to create issues to know if it's supported or not. I have none knowledge in JavaCC, so I hope you help me for that. 

Once Qute tolerant parser and language server will be implemented, it will be easy to do the same thing for FreeMarker and we will have a very robust tooling for FreeMarker.
